packages:
- '.'
- location:
    git: git@github.com:stackbuilders/scalendar.git
    commit: 01508a511d416af8069d351bdfa4cf83b55db401
  subdirs: []
  extra-dep: true
extra-deps:
- SCalendar-0.1.0.0
resolver: lts-8.19
