packages:
- '.'
- location:
    git: git@github.com:stackbuilders/scalendar.git
    commit: 12bba5cba60d1cbd84f12dcf5e187c88681b7d09
  subdirs: []
  extra-dep: true
extra-deps:
- scalendar-1.0.0
resolver: lts-8.19
