# The present workflow was made based on the following references:
# - https://github.com/stackbuilders/hapistrano/blob/master/.github/workflows/draft.yml
---
name: Draft

on:
  create:
    tags:
      - v*

concurrency:
  group: draft-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create draft release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            LICENSE
          draft: true
